#!/bin/bash

echo "🚀 Starting CoopCredit Microservices..."
docker-compose up --build -d

echo ""
echo "✅ Services started successfully!"
echo ""
echo "📊 Service Information:"
echo ""
echo "🗄️  PostgreSQL Database:"
echo "  - Host: localhost:5432"
echo "  - Database: coopcredit_db"
echo "  - User: coopcredit_user"
echo ""
echo "🎯 Risk Central Mock Service (Port 8081):"
echo "  - API: http://localhost:8081"
echo "  - Health: http://localhost:8081/actuator/health"
echo "  - Swagger UI: http://localhost:8081/swagger-ui.html"
echo "  - API Docs: http://localhost:8081/api-docs"
echo "  - Metrics: http://localhost:8081/actuator/metrics"
echo ""
echo "🏦 Creddit Application Service (Port 8080):"
echo "  - API: http://localhost:8080"
echo "  - Health: http://localhost:8080/actuator/health"
echo "  - Swagger UI: http://localhost:8080/swagger-ui.html"
echo "  - API Docs: http://localhost:8080/v3/api-docs"
echo ""
echo "📝 Example requests:"
echo ""
echo "  # Risk Evaluation:"
echo "  curl -X POST http://localhost:8081/risk-evaluation \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"documentId\":\"1017654311\",\"amount\":5000000,\"term\":36}'"
echo ""
echo "  # View logs:"
echo "  docker-compose logs -f"
echo ""

